services:
  web:
    build:
      dockerfile: ./BenchStoreMVC/Dockerfile
    container_name: BenchStore-web
    ports:
      - 15142:80
    volumes:
      - ./BenchStoreMVC/appsettings.Production.json:/app/appsettings.Production.json

  database:
    image: docker.io/postgres:16-alpine
    container_name: rust-iteration-06-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database-persistence:/var/lib/postgresql/data
    ports:
      - 15143:5432

volumes:
  database-persistence:
