# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pa200-alexh

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_15e242d71ca543c380aee420b9a51d64 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a5a7e7acda5e4d3fb0c0901ff15b318b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_15e242d71ca543c380aee420b9a51d64 }}/appsvc/staticsite:${{ github.sha }}
        file: ./BenchStoreMVC/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pa200-alexh'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9efacc57bb314afea13a1de859ff1959 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_15e242d71ca543c380aee420b9a51d64 }}/appsvc/staticsite:${{ github.sha }}'
